title: ␥the␥psyche␥lab
email: mark.adams@ed.ac.uk
description: >- 
  Psychological and Psychiatric Complex Trait Genetics Research Group
url: "https://psyche.systems"

social:
  - name: mastodon
    url: https://genomic.social/@markjamesadams
  - name: bluesky
    url: https://bsky.app/profile/markjamesadams.bsky.social
  - name: twitter
    url: https://twitter.com/mja
  - name: github
    url: https://github.com/mja

collections:
  members:
    output: true
  themes:
  projects:
  publications:

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
